server:
  port: 8080
spring:
  application:
    name: "Authentication"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  app:
    postgresql:
      host: localhost
      port: 5432
      database: authentication
      username: postgres
      password: postgrespws
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/authentication
    username: postgres
    password: postgrespws
    flyway:
      url: jdbc:postgresql://localhost:5432/authentication
      user: postgres
      password: postgrespws
      locations: classpath:db/migration
  logging:
    level:
      org.springframework: "INFO"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
