server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: "Authentication"
  devtools:
    add-properties: false
  app:
    postgresql:
      host: ${DB_HOST:db}
      port: ${DB_PORT:5432}
      database: ${DB_NAME:authentication}
      username: ${DB_USER:postgres}
      password: ${DB_PASSWORD:postgrespws}
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:authentication}}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgrespws}
    flyway:
      url: ${FLYWAY_URL:jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:authentication}}
      user: ${DB_USER:postgres}
      password: ${DB_PASSWORD:postgrespws}
      locations: classpath:db/migration
<<<<<<< HEAD

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8080}

jwt:
  secret: ${JWT_SECRET:this-is-a-very-long-32-byte-secret-key!!}
  expires-in-seconds: ${JWT_EXPIRES_IN:3600}
=======
  logging:
    level:
<<<<<<< HEAD
      co.com.bancolombia: INFO
      org.springframework.web: INFO
=======
      co.com.bancolombia: "INFO"
>>>>>>> e9327b0a8449ea6154e02b3317113961689f247a
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
jwt:
  secret: "this-is-a-very-long-32-byte-secret-key!!"
  expires-in-seconds: 3600
<<<<<<< HEAD
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html





=======
>>>>>>> e9327b0a8449ea6154e02b3317113961689f247a
>>>>>>> 64ae74362c4ef6e5c96ad00eb9499a158b0963b0
